### ISSUE TITLE
Upgrade to dependency-check-core 3.0.0

### ISSUE THREAD

**Issue by jeremylong** [livingsocial/lein-dependency-check#13]
Several breaking changes were made from 2.x to the 3.0.0 release. The primary change is that the settings is no longer a singleton and a few constructor and methods were changed. The [PR to upgrade the gradle plugin from 2.x to 3.0.0](https://github.com/jeremylong/dependency-check-gradle/pull/58/files) may provide a good roadmap.

The good news is that dependency-check-core is now threadsafe and you can have multiple instances running in parallel.

**Comment by dgknght** [comment]
Thanks @jeremylong . I've created PR #14 to implement the upgrade. If you could give it a quick look to see if I've missed anything important I would appreciate it much.

**Comment by jeremylong** [comment]
I'll do my best - but if I could write/read closure I would have just sent in a PR ;)

**Comment by dgknght** [comment]
Totally understandable. :)

**Comment by dgknght** [comment]
That's much cleaner on our side now. Thanks for your help, @jeremylong!
