### ISSUE TITLE
Minimum severity to throw option?

### ISSUE THREAD

**Issue by RutledgePaulV** [livingsocial/lein-dependency-check#18]
Hi,

Thanks for maintaining this plugin.

Our organization has a policy to address any high or critical issues according to the CVSS scale. This means that sometimes we choose not to immediately address low / medium issues. I'd like our build to fail if there are any issues above a particular CVSS score but otherwise just log and create the report.

Basically, I want the "failBuildOnCVSS" option documented here:
https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html#bodyColumn

Would you be interested in adding this feature? I may be able to create a PR.

**Comment by dgknght** [comment]
Sure, a PR would be great!

**Comment by RutledgePaulV** [comment]
Thanks! Created.

**Comment by dgknght** [comment]
Published in [version 1.1.1](https://clojars.org/com.livingsocial/lein-dependency-check/versions/1.1.1).
