### ISSUE TITLE
Dependency Check configuration modification?

### ISSUE THREAD

**Issue by ccuadrado** [livingsocial/lein-dependency-check#19]
I'm looking to overwrite the default dependency-check configuration in dependencycheck.properties in the underlying owasp dependency check jar so that it only executes the analyzers I want. There are certain dependencies in my project which are scanned by other CVE scanners and I don't want them scanned again. However placing a dependencycheck.properties file on the classpath doesn't disable the analyzers. Instead, should I modify `src/lein_dependency_check/core.clj` scan-files function to disable the dependency checks by reading from a file?

Any advice would be appreciated.

**Comment by CayvonH** [comment]
It seems if we add `(.mergeProperties settings <dependencycheck.properties-path>)` to `lein-dependency-check.core/scan-files` it'll work.

**Comment by ccuadrado** [comment]
Thanks!
