### ISSUE TITLE
Unable to connect to the database (if using outside Lein)

### ISSUE THREAD

**Issue by vemv** [livingsocial/lein-dependency-check#26]
Hi again,

I'm interested in using this as a library, as opposed to a Lein plugin.

Luckily, the code appears ready to use. But it fails in the following way:

![image](https://user-images.githubusercontent.com/1162994/52164691-9c24a100-26f5-11e9-89ad-27a212a74f48.png)

You can see my attempt  in the upper half, and its evaluation in the lower one.

Does it sound familiar?

Thanks - Victor

**Comment by vemv** [comment]
Hey there,

any luck with this one?

@dgknght

**Comment by dgknght** [comment]
@vemv, I took a quick glance at it, but I haven't had time to dig in yet. I'll see if I can't find some time to look at it this week.

**Comment by vemv** [comment]
This was due to Lein's dependency resolution placing some versions that the Java lib doesn't like.

And the Java lib likes to swallow many kinds of errors as `Unable to connect to the database`...

As a workaround, one can figure out lein-dependency-check's full dep tree (via lein pprint), and paste that into project.clj.
